version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    working_directory: ~/PatrimonioDev/PatrimonioDev
    steps:
      - checkout:
          path: ~/PatrimonioDev
      - run: 
          command: echo "Current directory $(ls)"
      - run: dotnet restore
      - run: dotnet dev-certs https --clean
      - run: dotnet dev-certs https -t
      - run: dotnet build

  build-and-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Install dependence commitlint-circle 
          command: yarn add @timbeyer/commitlint-circle --dev
      - run:
          name: Install dependence semantic-release 
          command: yarn add semantic-release --dev
      - run:
          name: Build
          command: yarn commitlint-circle
      - run:
          name: release
          command: yarn run semantic-release || true
      - run: 
          name: Auth With NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  sample: 
    jobs:
      - build
      - build-and-test
